### PR TITLE
Committed Structure-files and automated linters

### PR DESCRIPTION
**Pull request by alef-garrido**
Added .gitignore file with apprpiate lines to ignore node module files generated by npm.
Updated README.md file to comply with Microverse's template.
Added html and css main files (index.html and main.css) with basic structure and styling. 
Added test.md file and updated git-ignore file to ignore it.
Updated html and css file to pass linter's checks. No bug found, checks currently passed.

### CODE REVIEW

**Comment by Davidosky007** [comment]
# Hi @alef-garrido, 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
* I think you should have a descriptive pull request title with a short summary of all changes made in more details as stated in the project requirements.
* I suggest making all linter checks report no errors as this keeps your code clean and bug-free. 👍  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

# Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by alef-garrido** [comment]
Hello, 
I have changed the tittle and description of this request.
Also I've made the necessary changes to pass all the checks from the automated linters. 

However i have a doubt about the optional suggestions as i'm not sure about what the reviewer means about  "OPTIONAL prefix in every comment" 

Can i have a clarification or further explanation about that suggestion I'll greatly appreciate it.

**Comment by Davidosky007** [comment]
> Hello,
> I have changed the title and description of this request.
> Also I've made the necessary changes to pass all the checks from the automated linters.
> 
> However i doubt the optional suggestions as I'm not sure about what the reviewer means about "OPTIONAL prefix in every comment"
> 
> Can i have clarification or further explanation about that suggestion? I'll greatly appreciate it.

Good job making all the requested changes 👍 
About the optional suggestion, it's a suggestion that isn't part of the original project requirements, but a nice to have change you can add to your project to make it better. So, in this case, you don't have any optional suggestions. I hope my explanation is clear. thanks 🙏

**Review by descholar-ceo — APPROVED** [review]
# Status: Project approved :tada: :tada: :tada: :wine_glass: :champagne: :champagne: 
## Hi @alef-garrido   :handshake: :handshake: :handshake:

Your first project at Microverse is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
We are so proud of you, Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
